const moo = require("moo");

module.exports = moo.compile({
  Number: /(?:(?:(?:\d+\.\d*)|(?:\d*\.\d+))(?:[eE][+-]?\d+)?)|\d+/,
  Add: ["+"],
  Mult: ["*"],
  Sub: ["-"],
  ZDiv: ["//"],
  Div: ["/"],
  Mod: ["%"],
  ParOpen: ["("],
  ParClose: [")"],
  Equal: ["=="],
  Diff: ["!="],
  GTE: [">="],
  LTE: ["<="],
  GT: [">"],
  LT: ["<"],
  True: ["true"],
  False: ["false"],
  Not: ["!"],
  And: ["&&"],
  Or: ["||"],
  If: ["if"],
  Then: ["then"],
  Else: ["else"],
  Comma: [","],
  Identifier: /\w+/,
  WhiteSpace: /[ \t\f\v]+/,
});
